# Generated by Django 5.1.1 on 2024-09-09 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.TextField()),
                ('course_duration', models.TextField()),
                ('available_seat', models.PositiveIntegerField()),
                ('course_details', models.TextField()),
                ('course_available', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_department', to='department.department')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher', to='teacher.teacherprofile')),
            ],
        ),
    ]
